version: '3.8'

networks:
  bd2_network:
    driver: bridge

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filmes_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bd2_network

  populate:
    build: ./db
    container_name: populate_script
    volumes:
      - ./silver:/app/silver
    depends_on:
      - db
    networks:
      - bd2_network

volumes:
  postgres_data: